name: BeacmcStaffWork
version: '${project.version}'
main: com.beacmc.beacmcstaffwork.BeacmcStaffWork
api-version: 1.16
depend:
  - LuckPerms
softdepend:
  - PlaceholderAPI
author: beacmc
commands:
  staffwork:
    aliases:
      - sw
      - staffw
      - swork
  staffworkadmin:
    aliases:
      - swa
      - sworkadmin
